abstract: Testing for Singleton Class
author: 'Toni Prug <toni@irational.org>'
build_requires:
  Class::Singleton: 0
  Test::Builder::Tester: 0
distribution_type: module
generated_by: Module::Install version 0.55
license: gpl
name: Test-Singleton
no_index:
  directory:
    - inc
    - t
requires:
  Test::Builder: 0.16
  Test::More: 0.44
version: 1.02
